config/routes.rb
Rails.application.routes.draw do
  root 'sauces#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :sauces, only: [:index, :new, :create, :edit, :update, :destroy]

  get "/sauces/:id", to: "homes#index"
  get "/users/:id", to: "homes#index"

  namespace :api do
    namespace :v1 do 
      resources :sauces, only: [:show] do 
        resources :reviews, only: [:create, :destroy]
      end 
      resources :users, only: [:show]
      resources :votes, only: [:create]
    end 
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  validates :title, presence: true
  validates :rating, numericality: { minimum: 0, maximum: 5 }
  validates :heatIndex, numericality: { minimum: 0, maximum: 10 }
  validates :user_id, numericality: true
  
  belongs_to :sauce
  belongs_to :user

  has_many :votes
  has_many :users, through: :votes

  def total_karma
    self.votes.sum(:vote_type)
  end

  def my_sauce
    self.sauce
  end
end

app/models/sauce.rb
class Sauce < ApplicationRecord
  mount_uploader :image_url, SauceImageUploader

  validates :name, presence: true
  validates :brand, presence: true
  validates :image_url, presence: true
  validates :name, uniqueness: { scope: :brand }

  extend FriendlyId
  friendly_id :name_brand_slug, use: :slugged

  has_many :reviews

  def name_brand_slug
    [
      [:name, :brand]
    ]
  end

  def average_rating_text
    if self.reviews.length == 0
      return "No Reviews Yet"
    else
      avg = ((self.reviews.sum(:rating).to_f) / self.reviews.length).round(1)
      return "Average rating: #{avg} / 5.0"
    end
  end

  def sauce_image
    self.image_url.url
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :dippr_handle, presence: true, uniqueness: true, format: { without: /\s/ }
  validates :avatar, presence: true
  validates :role, presence: true

  has_many :votes

  extend FriendlyId
  friendly_id :dippr_handle, use: :slugged

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews 

  def admin?
    role == "admin"
  end

end

app/models/vote.rb
class Vote < ApplicationRecord
  validates :vote_type, numericality: { only_integer: true, greater_than_or_equal_to: -1, less_than_or_equal_to: 1, other_than: 0 }

  belongs_to :user
  belongs_to :review
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ApiController
  protect_from_forgery unless: -> {request.format.json? }
  before_action :authenticate_user
  before_action :authorize_user, except: [:create]
  
  def create
    review = Review.new(review_params)
    review.sauce_id = params[:sauce_id]
    review.user_id = current_user[:id]

    if review.save
      votes = review.votes
      payload = {**review.attributes, votes: votes, user: current_user}
      render json: {review: payload}
    else 
      render json: {error: review.errors.full_messages, status: :unprocessable_entity }
    end
  end

  def destroy
    review = Review.find(params[:id])

    if review.destroy
      render json: {status: 200}
    else
      render json: {error: "Unable to delete this review", status: :not_implemented}
    end
  end

  private 

  def authenticate_user
    if !user_signed_in?
      render json: {error: ["you must be signed in"]}
    end
  end

  def authorize_user
    if !user_signed_in? || !(current_user.id == Review.find(params['id']).user.id) && !(current_user.role == 'admin')
      render json: {error: ["Only admins have access to this feature"]}
    end
  end

  def review_params
    params.require(:review).permit(:title, :rating, :heatIndex, :body)
  end
end 

app/controllers/api/v1/sauces_controller.rb
class Api::V1::SaucesController < ApiController
  def show
    render json: Sauce.friendly.find(params[:id])
  end 
end 

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApiController
  def show
    render json: User.friendly.find(params[:id])
  end
end

app/controllers/api/v1/votes_controller.rb
class Api::V1::VotesController < ApiController
	before_action :authenticate_user

  def create
		existing_vote = Vote.find_by(user_id: current_user.id, review_id: params['review_id'])
    
    if existing_vote
      review = Review.find(params['review_id'])
      change_existing_vote(existing_vote, review)
    else
      create_new_vote
    end
  end

	private

	def authenticate_user
    if !user_signed_in?
      render json: {error: ["You must be signed in to vote on reviews!"]}
    end
  end

  def vote_params
    params.require(:vote).permit(:vote_type, :review_id)
  end

  def change_existing_vote(existing_vote, review)
    if existing_vote.vote_type === params['vote_type']
      existing_vote.destroy

      karma = review.total_karma
      vote = { vote_type: nil }
      payload = { vote: vote, karma: karma }

      render json: payload
    else
      existing_vote.update(vote_type: params['vote_type'])

      karma = review.total_karma
      payload = { vote: existing_vote, karma: karma}

      render json: payload
    end
  end

  def create_new_vote 
    vote_hash = vote_params.merge!({user_id: current_user.id})
    vote = Vote.new(vote_hash)

    if vote.save
      review = Review.find(vote.review_id)
      karma = review.total_karma
      payload = { vote: vote, karma: karma }

      render json: payload
    else
      render json: {error: "An error occurred."}
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
    # Prevent CSRF attacks by raising an exception.
    
    protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ::ActionController::Serialization

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:dippr_handle, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:dippr_handle, :avatar])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    
  end
end

app/controllers/sauces_controller.rb
class SaucesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :authorize_user, except: [:index, :new, :create]

  def index
    @sauces = Sauce.all    
  end

  def new
    @sauce = Sauce.new
  end

  def create
    @sauce = Sauce.new(sauce_params)

    if @sauce.save
      flash[:notice] = "You successfully added that sauce."
      redirect_to sauces_path
    else
      flash.now[:error] = @sauce.errors.full_messages.to_sentence 
      render :new
    end
  end

  def edit
    @sauce = Sauce.friendly.find(params[:id])
  end

  def update
    @sauce = Sauce.friendly.find(params[:id])

    if @sauce.update(sauce_params)
      flash[:notice] = "Sauce updated successfully"
      redirect_to sauces_path
    else
      flash.now[:error] = @sauce.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @sauce = Sauce.friendly.find(params[:id])

    if @sauce.destroy
      reviews = Review.where(sauce: @sauce)
      Vote.where(review: reviews).delete_all
      reviews.destroy_all
      
      flash[:notice] = "Sauce obliterated. The sauce is lost."
      redirect_to sauces_path
    else
      flash.now[:error] = "Unable to delete sauce"
      render :edit
    end

  end

  private

  def authorize_user
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Not Found")
    end
  end

  def sauce_params
    params.require(:sauce).permit(:name, :brand, :image_url, :description)
  end
end

app/views/homes/index.html.erb
<div id="app">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dippr</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/now" type="text/css"/>
  <script src="https://kit.fontawesome.com/54a2300b8c.js" crossorigin="anonymous"></script>
</head>
<body >

  <div>
    <div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
      <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
      <div class="title-bar-title">Menu</div>
    </div>
    <div class="top-bar grid-x" id="responsive-menu">
      <div class="cell small-3">
        <a href="/" class="mayo-text top-bar-appname top-bar-text-wrapper" >Dippr</a>
      </div>
      <div class="cell auto topbar-user-section grid-container">
        <div class="grid-x grid-margin-x right ketchup">
          <%- if current_user -%>
            <div class="cell auto text-right top-bar-text-wrapper mayo-text" > 
              Welcome,  <%= link_to "#{current_user.dippr_handle}", "/users/#{current_user.slug}", class: "mayo-text ketchup text-right top-bar-text" %>
              &nbsp; / &nbsp; 
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "mayo-text ketchup text-left top-bar-text" %>
            </div>
          <%- else -%>
            <div class="cell auto text-right top-bar-text-wrapper mayo-text" >
              <%= link_to 'Sign Up', new_user_registration_path, class: "mayo-text ketchup text-right top-bar-text" %> 
              &nbsp; / &nbsp; 
              <%= link_to 'Sign In', new_user_session_path, class: "mayo-text ketchup top-bar-text" %>
            </div>
          <%- end -%>
        </div>
      </div>
    </div>

  <%- flash.each do |key, value| -%>
    <div class="flash callout alert flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  
  <%- if Rails.env.development? || Rails.env.test? -%> 
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>
  
  <%= yield :extra_footer %>
</body>
</html>

app/views/sauces/edit.html.erb
<h1 class="page-header-text">Edit this sauce:</h1> 
<div class="form-tile callout" >
  <%= form_for @sauce do |f| %>
    <%= f.label :name, class: "form-label-text" %>
    <%= f.text_field :name %>
  
    <%= f.label :brand, class: "form-label-text" %>
    <%= f.text_field :brand %>
    
    <%= f.label :image_url, "Image URL", class: "form-label-text" %>  
    <%= f.file_field :image_url %>
    
    <%= f.label :description, class: "form-label-text" %>
    <%= f.text_field :description %>
    
		<div class="button-group now-font" >
			<%= f.submit class: "button success" %>
			<%= link_to "Obliterate this Sauce", sauce_path(@sauce), method: "DELETE", class: "button alert" %>
		</div>

  <% end %>

  <br>
  <%= link_to 'Back to Sauces', sauces_path, class: "ketchup-text" %>
</div>

app/views/sauces/index.html.erb
<div class='grid-container'>

  <div class=" new-sauce-button" >
    <h2 class="now-font text-center" > Welcome to <strong>Dippr</strong> </h2>
    <p class="now-font text-center"> A place for sauce enthusiasts to share their love for sauces, dips, and dressings.</p>
    <div class="button-wrapper" >
      <%= link_to '+ Add New Sauce', new_sauce_path, class: "button expanded mayo-text secondary bold" %>
    </div>
  </div>

  <div class='sauce-index-grid grid-x grid-margin-x grid-margin-y'>

    <% @sauces.each do |sauce| %>

      <div class='sauce-index-cell callout cell small-12 medium-6 large-4 napkin'>
        <a href=<%="/sauces/#{sauce.slug}"%>>
          <%= image_tag sauce.sauce_image, class: "sauce-card-image" %>
          <h3 class="sauce-card-title ketchup-text" > <strong><%= sauce.name %></strong> </h3>
          <h4 class="ketchup-text sauce-card-title" > (<%= sauce.brand %>) </h4>
          <p class="now-font ketchup-text" ><%= sauce.average_rating_text %></p>
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <%= link_to "Edit Sauce", edit_sauce_path(sauce), class: "button expanded alert" %>
            <% end %>
          <% end %>
        </a>
      </div>

    <% end %>

  </div>
</div>

app/views/sauces/new.html.erb
<h1 class="page-header-text">Add a new sauce:</h1> 
<div class="form-tile callout" >
  <%= form_for @sauce do |f| %>
    <%= f.label :name, class: "form-label-text" %>
    <%= f.text_field :name %>
  
    <%= f.label :brand, class: "form-label-text" %>
    <%= f.text_field :brand %>
    
    <%= f.label :image_url, "Image URL", class: "form-label-text" %>  
    <%= f.file_field :image_url %>
    
    <%= f.label :description, class: "form-label-text" %>
    <%= f.text_field :description %>
    
    <%= f.submit class: "button secondary" %>
  <% end %>
  <br>
  <%= link_to 'Back to Sauces', sauces_path, class: "ketchup-text" %>
</div>